# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee673fd131e28869ac198e96a9f9217c552de0efd8728a6e7c52da5fc373365d60042cee10d1f39ad9a0456fe1144b34dfdaeda1d0ce7dd2c4ce0f1c703166d2

test:
  secret_key_base: a0a178de710633881df24d4fd3da47fb5a1a5bf04dd93fac55dc0db777ba593d5008732371fddf1054797186142bbb4f61031fffd59cd486aef78660e6b03001

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
